export const DEFENDERSELECT = "DEFENDERSELECT";
export const GOALKEEPERSELECT = "GOALKEEPERSELECT";
export const MIDFIELDERSELECT = "MIDFIELDERSELECT";
export const ATTACKERSELECT = "ATTACKERSELECT";
export const HIDEBACKDROP = "HIDEBACKDROP";
export const SHOWBACKDROP = "SHOWBACKDROP";
