import TeamPics from "./teampics/teampics";
export const allTeams = [
  {
    id: "1a",
    name: "Chelsea",
    players: {
      goalKeeper: "Cech",
      defenders: ["Terry", "Cole"],
      midfielders: ["Lampard", "Makelele"],
      attackers: ["Drogba", "Hazard"],
    },
    image: TeamPics[0],
    league: "England",
  },
  {
    id: "2b",
    name: "Manchester United",
    players: {
      goalKeeper: "Schmeicel",
      defenders: ["Ferdinand", "Vidic"],
      midfielders: ["Scholes", "Cantona"],
      attackers: ["Rooney", "York"],
    },
    image: TeamPics[2],
    league: "England",
  },
  {
    id: "3c",
    name: "Arsenal",
    players: {
      goalKeeper: "Seaman",
      defenders: ["Campbell", "Adams"],
      midfielders: ["Vieira", "Fabregas"],
      attackers: ["Henry", "Bergkamp"],
    },
    image: TeamPics[1],
    league: "England",
  },
  {
    id: "4d",
    name: "Liverpool",
    players: {
      goalKeeper: "Becker",
      defenders: ["Vandijk", "Carragher"],
      midfielders: ["Gerrard", "Alonso"],
      attackers: ["Torres", "Owen"],
    },
    image: TeamPics[4],
    league: "England",
  },
  {
    id: "5e",
    name: "Juventus",
    players: {
      goalKeeper: "Buffon",
      defenders: ["Cannavaro", "Thuram"],
      midfielders: ["Nedved", "Pirlo"],
      attackers: ["Del Piero", "Trezeguet"],
    },
    image: TeamPics[3],
    league: "Italy",
  },
  {
    id: "6f",
    name: "Ac Milan",
    players: {
      goalKeeper: "Dida",
      defenders: ["Nesta", "Maldini"],
      midfielders: ["Kaka", "Seedorf"],
      attackers: ["Shevchenko", "Zlatan"],
    },
    image: TeamPics[5],
    league: "Italy",
  },
  {
    id: "7g",
    name: "Inter Milan",
    players: {
      goalKeeper: "Cesar",
      defenders: ["Lucio", "Zanetti"],
      midfielders: ["Schneider", "Cambiasso"],
      attackers: ["Eto'o", "Ronaldo"],
    },
    image: TeamPics[6],
    league: "Italy",
  },
  {
    id: "8h",
    name: "Barcelona",
    players: {
      goalKeeper: "Valdes",
      defenders: ["Puyol", "Pique"],
      midfielders: ["Xavi", "Iniesta"],
      attackers: ["Messi", "Ronaldinho"],
    },
    image: TeamPics[10],
    league: "Spain",
  },
  {
    id: "9i",
    name: "Real Madrid",
    players: {
      goalKeeper: "Casillas",
      defenders: ["Ramos", "Roberto Carlos"],
      midfielders: ["Zidane", "Figo"],
      attackers: ["Cr Ronaldo", "Raul"],
    },
    image: TeamPics[7],
    league: "Spain",
  },
  {
    id: "10j",
    name: "Bayern Munich",
    players: {
      goalKeeper: "Neuer",
      defenders: ["Alaba", "Lahm"],
      midfielders: ["Ribery", "Thiago"],
      attackers: ["Lewandovski", "Robben"],
    },
    image: TeamPics[9],
    league: "Other",
  },
  {
    id: "11k",
    name: "PSG",
    players: {
      goalKeeper: "Navas",
      defenders: ["Thiago Silva", "Kimpembe"],
      midfielders: ["Verrati", "Di Maria"],
      attackers: ["Neymar", "Mbappe"],
    },
    image: TeamPics[8],
    league: "Other",
  },
];
