export const ADDPEPPERONI = "ADDPEPPERONI";
export const REDUCEPEPPERONI = "REDUCEPEPPERONI";

export const ADDCHEESESTEAK = "ADDCHEESESTEAK";
export const REDUCECHEESESTEAK = "REDUCECHEESESTEAK";

export const ADDMARINARA = "ADDMARINARA";
export const REDUCEMARINARA = "REDUCEMARINARA";

export const ADDCHEESEBURGER = "ADDCHEESEBURGER";
export const REDUCECHEESEBURGER = "REDUCECHEESEBURGER";

export const ADDBIGMAC = "ADDBIGMAC";
export const REDUCEBIGMAC = "REDUCEBIGMAC";

export const ADDVEGIBURGER = "ADDVEGIBURGER";
export const REDUCEVEGIBURGER = "REDUCEVEGIBURGER";

export const ADDHOTDOG = "ADDHOTDOG";
export const REDUCEHOTDOG = "REDUCEHOTDOG";

export const ADDSALAMI = "ADDSALAMI";
export const REDUCESALAMI = "REDUCESALAMI";

export const ADDCORDONBLEU = "ADDCORDONBLEU";
export const REDUCECORDONBLEU = "REDUCECORDONBLEU";

export const ADDFRIEDCHICKEN = "ADDFRIEDCHICKEN";
export const REDUCEFRIEDCHICKEN = "REDUCEFRIEDCHICKEN";
